source 'https://rubygems.org'

gem 'sinatra', '3.1.0'
gem 'pg',      '1.5.3'
gem 'composite_primary_keys', '11.3.1'
gem 'sequel', '5.72.0'
gem 'bcrypt', '3.1.19'
gem 'dotenv', '2.8.1'
gem 'puma', '6.3.1'
gem 'rake', '13.0.6'
gem 'rerun', '0.14.0'
gem 'sinatra-contrib', '3.1.0'
gem 'sinatra-cross_origin'
gem 'rack-cors'

group :test do
  gem 'rspec'
  gem 'rack-test'
end

