# Rakefile

require 'rake'
require_relative './app' # Replace with the correct path to your Sinatra app

namespace :test do
  task :run do
    require 'rspec'
    RSpec::Core::Runner.run(['spec']) # Run your RSpec tests
  end
end

task :start => 'test:run' do
  exec('puma -C config/puma.rb') # Start your Sinatra application with Puma
end

#Start command: rake start