version: '3'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - '${CLIENT_PORT:-3000}:80'
    environment:
      - CLIENT_PORT=${CLIENT_PORT:-3000}
  server:
    container_name: server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - '${SERVER_PORT:-8080}:80'
    environment:
      - SERVER_PORT=${SERVER_PORT:-8080}
